### ISSUE TITLE
Offset gets maxed out when switching from another user account...

### ISSUE THREAD

**Issue by rsaid99** [OCJvanDijk/Brightness-Sync#11]
v2.2.0 Beta 1

1) Set offset on external monitor to a low brightness using external keyboard.
2) Switch to another user's account (not running Brightness-Sync).
3) Alter the brightness using external keyboard.
4) Switch back to the first account (the one running Brightness-Sync).
5) Observe that brightness (and offset) on external monitor is now maximum.

Everything else has been working great so far.

**Comment by OCJvanDijk** [comment]
Good catch! Should be fixed in beta 2.
