### ISSUE TITLE
Read from iPhone/iPad sensor?

### ISSUE THREAD

**Issue by magnum6actual** [OCJvanDijk/Brightness-Sync#16]
I have a Mac mini with 2x LG UltraFine monitors so I've got nothing to read from. It would be really cool to be able to get the ambient light reading from a close by iPhone/iPad to be able to adjust the brightness of my monitors.  Certainly beyond my capabilities, but thinking it wouldn't be too difficult for someone who knows what they are doing.

**Comment by OCJvanDijk** [comment]
That's a cool idea, but unfortunately not trivial and outside of the scope of this project.
