### ISSUE TITLE
Read from 2nd Gen LG Ultrafine 5K? 

### ISSUE THREAD

**Issue by paulsri** [OCJvanDijk/Brightness-Sync#17]
I have 2 x 1st Gen 5K's and 1 x 2nd Gen 5K. Would this utility be able to sync the 2 x 1st Gen 5Ks' brightness levels with the single 2nd Gen 5K, since it's the only one of the three that can automatically adjust its own brightness based on its ambient light sensor? Thanks!

**Comment by OCJvanDijk** [comment]
That's very doable and shouldn't require a big change at all, the problem is I can't really test it because I don't have access to a 2nd gen UltraFine.

You can help by posting some diagnostics about your monitors here. With all your screens attached, you can open the Brightness Sync menu and press Command+C to copy the diagnostics to your clipboard (the menu will close). Then you can paste them here.

**Comment by paulsri** [comment]
That's awesome! Thank you so much for being willing to try! I'm happy to test as much as you need me to. In fact, right now I'm having the problem of the 2nd gen dimming while the other two 1st gens staying bright. So I probably need this more than I thought, haha! Diagnostics attached. Thanks again!

[diagnostics.txt](https://github.com/OCJvanDijk/Brightness-Sync/files/4907547/diagnostics.txt)

**Comment by OCJvanDijk** [comment]
Try out [2.3.0-beta.1](https://github.com/OCJvanDijk/Brightness-Sync/releases/tag/v2.3.0-beta.1)!
It's a bit rough but for your particular setup it should work.

**Comment by paulsri** [comment]
Wow, it works like a charm! Thank you so much!! Not complaining, but small issue is that the 1st gen sliders don't move, so they don't reflect their actual brightness. eg, the 1st gen monitors definitely read and copy the brightness of the 2nd gen, but if you look at their brightness sliders, it doesn't match. Not sure if that's something you have control over or not?

**Comment by paulsri** [comment]
also, just read the release notes for v2.2.0, not sure if i'm supposed to unlock the brightness offset?

**Comment by OCJvanDijk** [comment]
> Wow, it works like a charm! Thank you so much!! Not complaining, but small issue is that the 1st gen sliders don't move, so they don't reflect their actual brightness. eg, the 1st gen monitors definitely read and copy the brightness of the 2nd gen, but if you look at their brightness sliders, it doesn't match. Not sure if that's something you have control over or not?

Yeah, the sliders don't update in real-time, nothing I can do about that. For me they do update when I close and open the sliders again.

> also, just read the release notes for v2.2.0, not sure if i'm supposed to unlock the brightness offset?

I don't think I can explain it any better than I tried in those release notes 😅. It's a bit hard to explain, "lock" and "offset" might not be the best words for it but it's the best I could come up with. Anyway, if you just want all your monitors to have the exact same brightness all the time, just keep the lock on.

**Comment by OCJvanDijk** [comment]
With "exact same brightness all the time", I mean they will match each other's brightness. They will still adjust to ambient light and user changes.

**Comment by OCJvanDijk** [comment]
I made another attempt at explaining it better in the README.

**Comment by paulsri** [comment]
Oh, neat! I just tried exiting the Display Properties and going back in, and I _do_ see the sliders at their new setting :) Thanks for the tip!

**Comment by paulsri** [comment]
Thank you for updating the README -- super clear now!
