### ISSUE TITLE
Cannot adjust brightness at all on LG Ultrafine 5K 27MD5KL-B

### ISSUE THREAD

**Issue by BinaryDennis** [OCJvanDijk/Brightness-Sync#19]
Hi
I have just bought the latest version of LG Ultrafine 5K, 27MD5KL-B. Im using it with my MacBook Pro 16" 2019.

But I cannot control the brightness of my LG screen at all, no matter what I do, it won't get brighter or darker. There are no overlay brightness-indicators showing up on the LG screen as it is on my Macbook when I adjust its brightness.

The LG screen is set on a very low-brightness so it's very frustrating not being able to increase it.

When I run the latest beta of your app.

<img width="284" alt="Screenshot 2020-08-25 at 10 33 17" src="https://user-images.githubusercontent.com/814063/91151771-64f25800-e6be-11ea-9aa0-a53e5512d0b9.png">

```
[69734662: Optional({
    DisplayBacklight = 500;
    DisplayBluePointX = "0.1503906";
    DisplayBluePointY = "0.05175781";
    DisplayBrightReflection = 505;
    DisplayBundleURL = "/System/Library/Displays/";
    DisplayDarkReflection = "1.1";
    DisplayFixedPixelFormat = 1;
    DisplayGreenPointX = "0.2646484";
    DisplayGreenPointY = "0.6904297";
    DisplayHorizontalImageSize = 340;
    DisplayLeakage = "0.419";
    DisplayLowestLevel = 2;
    DisplayLowestMeasured = "0.4323";
    DisplayProductID = 41028;
    DisplayProductName =     {
        ar = "\U200fLCD \U0645\U0644\U0648\U0646\U0629";
        "ca_ES" = "LCD en color";
        "cs_CZ" = "Barevn\U00fd LCD";
        "da_DK" = "LCD-farvesk\U00e6rm";
        "de_DE" = "Farb-LCD";
        "el_GR" = "\U0388\U03b3\U03c7\U03c1\U03c9\U03bc\U03b7 \U03bf\U03b8\U03cc\U03bd\U03b7 LCD";
        "en_AU" = "Colour LCD";
        "en_GB" = "Colour LCD";
        "en_US" = "Color LCD";
        "es_ES" = "LCD color";
        "es_XL" = "LCD color";
        "fi_FI" = "V\U00e4ri-LCD";
        "fr_CA" = "ACL couleur";
        "fr_FR" = "LCD couleur";
        "he_IL" = "\U200fLCD \U05e6\U05d1\U05e2\U05d5\U05e0\U05d9";
        "hi_IN" = "\U0930\U0902\U0917\U0940\U0928 LCD";
        "hr_HR" = "LCD u boji";
        "hu_HU" = "Sz\U00ednes LCD";
        id = "LCD Warna";
        "it_IT" = "LCD colori";
        "ja_JP" = "\U30ab\U30e9\U30fcLCD";
        "ko_KR" = "\Uceec\Ub7ec LCD";
        ms = "Warna LCD";
        "nb_NO" = "Farge-LCD";
        "nl_NL" = "Kleuren-LCD";
        "pl_PL" = "Kolor LCD";
        "pt_BR" = "LCD Colorido";
        "pt_PT" = "LCD a Cores";
        "ro_RO" = "LCD color";
        "ru_RU" = "\U0426\U0432\U0435\U0442\U043d\U043e\U0439 \U0416\U041a-\U0434\U0438\U0441\U043f\U043b\U0435\U0439";
        "sk_SK" = "Farebn\U00fd LCD";
        "sv_SE" = "F\U00e4rg-LCD";
        "th_TH" = "LCD \U0e2a\U0e35";
        "tr_TR" = "Renkli LCD";
        "uk_UA" = "\U041a\U043e\U043b\U044c\U043e\U0440\U043e\U0432\U0438\U0439 LCD";
        "vi_VN" = "LCD M\U00e0u";
        "zh_CN" = "\U5f69\U8272LCD";
        "zh_TW" = "\U5f69\U8272LCD";
    };
    DisplayRedPointX = "0.6796875";
    DisplayRedPointY = "0.3203125";
    DisplaySubPixelLayout = 1;
    DisplayVendorID = 1552;
    DisplayVerticalImageSize = 220;
    DisplayViewAngleAffectsGamma = 1;
    DisplayWeekManufacture = 36;
    DisplayWhiteGamma = "2.2";
    DisplayWhitePointX = "0.3125";
    DisplayWhitePointY = "0.3291016";
    DisplayYearManufacture = 2019;
    IODisplayAttributes = {length = 40, bytes = 0x67617476 00000000 73676c66 04000000 ... 676c6664 00000000 };
    IODisplayConnectFlags = {length = 4, bytes = 0x00080000};
    IODisplayEDID = {length = 256, bytes = 0x00ffffff ffffff00 061044a0 00000000 ... 00000000 00000490 };
    IODisplayEDIDOriginal = {length = 256, bytes = 0x00ffffff ffffff00 061044a0 00000000 ... 00000000 00000490 };
    IODisplayHasBacklight = 1;
    IODisplayIsDigital = 1;
    IODisplayIsHDMISink = 0;
    IODisplayLocation = "IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/PEG0@1/IOPP/EGP0@0/IOPP/EGP1@0/IOPP/GFX0@0/AMDRadeonX6000_AmdRadeonControllerNavi14/ATY,Boa@0/display0/AppleBacklightDisplay";
    IODisplayMobileBLTable = {length = 36, bytes = 0x00110000 02900344 043d0592 076509e4 ... 583a7a96 aae1eeed };
    IODisplayPrefsKey = "Alias:0/AppleBacklightDisplay-610-a044";
    IOFBTransform = 0;
    IOGFlags = 4;
    "display-refresh-rate-policy" = {length = 8, bytes = 0x0000000000000001};
    "display-resolution-preview-icon" = "/System/Library/Displays/Contents/Resources/Overrides/DisplayVendorID-610/DisplayProductID-a044-9d9da0.tiff";
    "display-rotation-policy" = {length = 8, bytes = 0x0000000000000001};
    dspc =     (
        {length = 18, bytes = 0xd5910050c08038700820980859d71000001a},
        {length = 18, bytes = 0xe7910050c080c2710820980859d71000001a},
        {length = 18, bytes = 0xdc910050c08024720820980859d71000001a},
        {length = 18, bytes = 0xe4910050c08027720820980859d71000001a}
    );
    "edid-patches" =     (
                {
            data = {length = 36, bytes = 0x00000010 00000000 00000000 00000000 ... 00000000 00000000 };
            offset = 90;
        }
    );
    "resolution-preview-height" = 96;
    "resolution-preview-width" = 154;
    "resolution-preview-x" = 36;
    "resolution-preview-y" = 65;
    "scale-resolutions" =     (
        {length = 8, bytes = 0x0000100000000a00},
        {length = 8, bytes = 0x00000e00000008c0},
        {length = 8, bytes = 0x00000c0000000780},
        {length = 8, bytes = 0x00000a8000000690},
        {length = 8, bytes = 0x00000900000005a0},
        {length = 16, bytes = 0x00000a00000006400000000100200000},
        {length = 16, bytes = 0x00000a00000005a00000000100200000},
        {length = 16, bytes = 0x00000780000004b00000000100200000},
        {length = 16, bytes = 0x00000780000004380000000100200000},
        {length = 16, bytes = 0x00000500000002d00000000100200000},
        {length = 12, bytes = 0x000006720000041a00000001},
        {length = 12, bytes = 0x000005a00000038400000001},
        {length = 12, bytes = 0x000005000000032000000001},
        {length = 12, bytes = 0x00000480000002d000000001},
        {length = 12, bytes = 0x000004000000030000000001},
        {length = 12, bytes = 0x000003480000020d00000001},
        {length = 12, bytes = 0x000003200000025800000001},
        {length = 12, bytes = 0x00000280000001e000000001},
        {length = 16, bytes = 0x00000f00000009600000000900a00000},
        {length = 16, bytes = 0x00000d20000008340000000900a00000},
        {length = 16, bytes = 0x00000b40000007080000000900a00000},
        {length = 16, bytes = 0x00000a00000006400000000900a00000},
        {length = 16, bytes = 0x00000800000005000000000900a00000},
        {length = 16, bytes = 0x00000780000004b00000000900a00000},
        {length = 16, bytes = 0x00000780000004380000000900200000},
        {length = 16, bytes = 0x00000500000002d00000000900200000}
    );
    slopeLimitGamma = 0;
    "target-default-ppmm" = "10.39";
}), 458635451: Optional({
    ContainerID = "DC8846F4-4A9F-45B5-B4B9-B43D7DE1CA37";
    DisplayBluePointX = "0.1503906";
    DisplayBluePointY = "0.05957031";
    DisplayBrightnessAffectsGamma = 1;
    DisplayBundleURL = "/System/Library/Displays/";
    DisplayGreenPointX = "0.2646484";
    DisplayGreenPointY = "0.6904297";
    DisplayHasHardwareBrightnessSmoothing = 1;
    DisplayHorizontalImageSize = 600;
    DisplayPort =     {
        PowerValue = 5;
    };
    DisplayProductID = 23412;
    DisplayProductName =     {
        ar = "LG UltraFine";
        "ca_ES" = "LG UltraFine";
        "cs_CZ" = "LG UltraFine";
        "da_DK" = "LG UltraFine";
        "de_DE" = "LG UltraFine";
        "el_GR" = "LG UltraFine";
        "en_AU" = "LG UltraFine";
        "en_GB" = "LG UltraFine";
        "en_US" = "LG UltraFine";
        "es_ES" = "LG UltraFine";
        "es_XL" = "LG UltraFine";
        "fi_FI" = "LG UltraFine";
        "fr_CA" = "LG UltraFine";
        "fr_FR" = "LG UltraFine";
        "he_IL" = "LG UltraFine";
        "hi_IN" = "LG UltraFine";
        "hr_HR" = "LG UltraFine";
        "hu_HU" = "LG UltraFine";
        id = "LG UltraFine";
        "it_IT" = "LG UltraFine";
        "ja_JP" = "LG UltraFine";
        "ko_KR" = "LG UltraFine";
        ms = "LG UltraFine";
        "nb_NO" = "LG UltraFine";
        "nl_NL" = "LG UltraFine";
        "pl_PL" = "LG UltraFine";
        "pt_BR" = "LG UltraFine";
        "pt_PT" = "LG UltraFine";
        "ro_RO" = "LG UltraFine";
        "ru_RU" = "LG UltraFine";
        "sk_SK" = "LG UltraFine";
        "sv_SE" = "LG UltraFine";
        "th_TH" = "LG UltraFine";
        "tr_TR" = "LG UltraFine";
        "uk_UA" = "LG UltraFine";
        "vi_VN" = "LG UltraFine";
        "zh_CN" = "LG UltraFine";
        "zh_TW" = "LG UltraFine";
    };
    DisplayRedPointX = "0.6796875";
    DisplayRedPointY = "0.3203125";
    DisplaySerialNumber = 320951;
    DisplayVendorID = 7789;
    DisplayVerticalImageSize = 340;
    DisplayWeekManufacture = 6;
    DisplayWhiteGamma = "2.2";
    DisplayWhitePointX = "0.3125";
    DisplayWhitePointY = "0.3291016";
    DisplayYearManufacture = 2020;
    IODisplayAttributes = {length = 40, bytes = 0x67617476 00000000 73676c66 04000000 ... 676c6664 00000000 };
    IODisplayConnectFlags = {length = 4, bytes = 0x00000000};
    IODisplayEDID = {length = 256, bytes = 0x00ffffff ffffff00 9e6d745b b7e50400 ... 00000000 00005490 };
    IODisplayEDIDOriginal = {length = 256, bytes = 0x00ffffff ffffff00 9e6d745b b7e50400 ... 00000000 00005490 };
    IODisplayIsDigital = 1;
    IODisplayIsHDMISink = 0;
    IODisplayLocation = "IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/PEG0@1/IOPP/EGP0@0/IOPP/EGP1@0/IOPP/GFX0@0/AMDRadeonX6000_AmdRadeonControllerNavi14/ATY,Boa@1/display0/AppleDisplay";
    IODisplayPrefsKey = "IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/PEG0@1/IOPP/EGP0@0/IOPP/EGP1@0/IOPP/GFX0@0/AMDRadeonX6000_AmdRadeonControllerNavi14/ATY,Boa@1/display0/AppleDisplay-9e6d-5b74";
    IOFBTransform = 0;
    IOGFlags = 4;
    "display-icon" = "/System/Library/Displays/Contents/Resources/Overrides/DisplayVendorID-1e6d/DisplayProductID-5b74.icns";
    "display-resolution-preview-icon" = "/System/Library/Displays/Contents/Resources/Overrides/DisplayVendorID-1e6d/DisplayProductID-5b74.tiff";
    "resolution-preview-height" = 114;
    "resolution-preview-width" = 202;
    "resolution-preview-x" = 11;
    "resolution-preview-y" = 47;
    "scale-resolutions" =     (
        {length = 8, bytes = 0x0000190000000e10},
        {length = 8, bytes = 0x0000168000000ca8},
        {length = 8, bytes = 0x0000140000000b40},
        {length = 8, bytes = 0x0000100000000900},
        {length = 8, bytes = 0x00000c8000000708},
        {length = 16, bytes = 0x00001000000008700000000100200000},
        {length = 16, bytes = 0x00000f00000008700000000100200000},
        {length = 16, bytes = 0x00000a00000006400000000100200000},
        {length = 16, bytes = 0x00000780000004b00000000100200000},
        {length = 16, bytes = 0x000006900000041a0000000100200000},
        {length = 16, bytes = 0x00000500000003200000000100200000},
        {length = 12, bytes = 0x00000b400000065400000001},
        {length = 12, bytes = 0x00000a00000005a000000001},
        {length = 12, bytes = 0x000008000000048000000001},
        {length = 12, bytes = 0x000007800000043800000001},
        {length = 12, bytes = 0x00000640000004b000000001},
        {length = 12, bytes = 0x000006400000038400000001},
        {length = 12, bytes = 0x000005a00000032a00000001},
        {length = 12, bytes = 0x00000540000002f400000001},
        {length = 12, bytes = 0x000005000000040000000001},
        {length = 12, bytes = 0x00000500000002d000000001},
        {length = 12, bytes = 0x000004000000030000000001},
        {length = 12, bytes = 0x000004000000024000000001},
        {length = 12, bytes = 0x000003c00000025800000001},
        {length = 12, bytes = 0x000003c00000021c00000001},
        {length = 12, bytes = 0x000003480000020c00000001},
        {length = 12, bytes = 0x000003200000025800000001},
        {length = 12, bytes = 0x00000280000001e000000001},
        {length = 16, bytes = 0x0000190000000e100000000900a00000},
        {length = 16, bytes = 0x0000168000000ca80000000900a00000},
        {length = 16, bytes = 0x0000140000000b400000000900a00000},
        {length = 16, bytes = 0x00001000000009000000000900a00000},
        {length = 16, bytes = 0x00000c80000007080000000900a00000}
    );
    slopeLimitGamma = 0;
})]
```

**Comment by OCJvanDijk** [comment]
I think I need some clarification.
Can you control the brightness of your 2nd gen UltraFine without the Brightness Sync app running?
What are you trying to achieve with this app? Shouldn't the 2nd gen UltraFine do automatic brightness by itself?

Currently the latest beta is set to ignore the 2nd gen UltraFine completely in your case. I thought the automatic brightness feature of the 2nd gen displays would mean this app wasn't needed anymore for those. As in #18, seems like there still is demand for syncing to 2nd gen displays though.

For now, if you just want to sync the brightness from your built-in display to your 2nd gen UltraFine display, you would need to download v2.2.0

**Comment by BinaryDennis** [comment]
Update: I unplugged and replugged the LG screen and restarted my MacBook pro. After this, I finally saw a brightness control for the LG screen in System Preferences (see the attached image). The brightness control was not there before?!

Anyways, Isn't the LG screen suppose to auto-adjust its brightness based on the MacBooks brightness?  So when I change my MacBooks brightness via the TouchBar, nothing happens on the LG screen. 


<img width="1397" alt="Screenshot 2020-08-26 at 13 37 12" src="https://user-images.githubusercontent.com/814063/91299057-5630a180-e7a1-11ea-9f4a-08d728b4a9f3.png">

**Comment by BinaryDennis** [comment]
I now tried with version 2.2.0, and Im very happy to say the LG screen updates its brightness based on Macbooks brightness, awesome! 🥳 

Great util app you built! 

However, very very disappointing that LG/MacOS to failed with auto-syncing of brightness

**Comment by vv-m** [comment]
> Hi I have just bought the latest version of LG Ultrafine 5K, 27MD5KL-B. Im using it with my MacBook Pro 16" 2019.
> 
> But I cannot control the brightness of my LG screen at all, no matter what I do, it won't get brighter or darker. There are no overlay brightness-indicators showing up on the LG screen as it is on my Macbook when I adjust its brightness.
> 
> The LG screen is set on a very low-brightness so it's very frustrating not being able to increase it.
> 
> When I run the latest beta of your app.
> 
> <img alt="Screenshot 2020-08-25 at 10 33 17" width="284" src="https://user-images.githubusercontent.com/814063/91151771-64f25800-e6be-11ea-9aa0-a53e5512d0b9.png">
> 
> ```
> [69734662: Optional({
>     DisplayBacklight = 500;
>     DisplayBluePointX = "0.1503906";
>     DisplayBluePointY = "0.05175781";
>     DisplayBrightReflection = 505;
>     DisplayBundleURL = "/System/Library/Displays/";
>     DisplayDarkReflection = "1.1";
>     DisplayFixedPixelFormat = 1;
>     DisplayGreenPointX = "0.2646484";
>     DisplayGreenPointY = "0.6904297";
>     DisplayHorizontalImageSize = 340;
>     DisplayLeakage = "0.419";
>     DisplayLowestLevel = 2;
>     DisplayLowestMeasured = "0.4323";
>     DisplayProductID = 41028;
>     DisplayProductName =     {
>         ar = "\U200fLCD \U0645\U0644\U0648\U0646\U0629";
>         "ca_ES" = "LCD en color";
>         "cs_CZ" = "Barevn\U00fd LCD";
>         "da_DK" = "LCD-farvesk\U00e6rm";
>         "de_DE" = "Farb-LCD";
>         "el_GR" = "\U0388\U03b3\U03c7\U03c1\U03c9\U03bc\U03b7 \U03bf\U03b8\U03cc\U03bd\U03b7 LCD";
>         "en_AU" = "Colour LCD";
>         "en_GB" = "Colour LCD";
>         "en_US" = "Color LCD";
>         "es_ES" = "LCD color";
>         "es_XL" = "LCD color";
>         "fi_FI" = "V\U00e4ri-LCD";
>         "fr_CA" = "ACL couleur";
>         "fr_FR" = "LCD couleur";
>         "he_IL" = "\U200fLCD \U05e6\U05d1\U05e2\U05d5\U05e0\U05d9";
>         "hi_IN" = "\U0930\U0902\U0917\U0940\U0928 LCD";
>         "hr_HR" = "LCD u boji";
>         "hu_HU" = "Sz\U00ednes LCD";
>         id = "LCD Warna";
>         "it_IT" = "LCD colori";
>         "ja_JP" = "\U30ab\U30e9\U30fcLCD";
>         "ko_KR" = "\Uceec\Ub7ec LCD";
>         ms = "Warna LCD";
>         "nb_NO" = "Farge-LCD";
>         "nl_NL" = "Kleuren-LCD";
>         "pl_PL" = "Kolor LCD";
>         "pt_BR" = "LCD Colorido";
>         "pt_PT" = "LCD a Cores";
>         "ro_RO" = "LCD color";
>         "ru_RU" = "\U0426\U0432\U0435\U0442\U043d\U043e\U0439 \U0416\U041a-\U0434\U0438\U0441\U043f\U043b\U0435\U0439";
>         "sk_SK" = "Farebn\U00fd LCD";
>         "sv_SE" = "F\U00e4rg-LCD";
>         "th_TH" = "LCD \U0e2a\U0e35";
>         "tr_TR" = "Renkli LCD";
>         "uk_UA" = "\U041a\U043e\U043b\U044c\U043e\U0440\U043e\U0432\U0438\U0439 LCD";
>         "vi_VN" = "LCD M\U00e0u";
>         "zh_CN" = "\U5f69\U8272LCD";
>         "zh_TW" = "\U5f69\U8272LCD";
>     };
>     DisplayRedPointX = "0.6796875";
>     DisplayRedPointY = "0.3203125";
>     DisplaySubPixelLayout = 1;
>     DisplayVendorID = 1552;
>     DisplayVerticalImageSize = 220;
>     DisplayViewAngleAffectsGamma = 1;
>     DisplayWeekManufacture = 36;
>     DisplayWhiteGamma = "2.2";
>     DisplayWhitePointX = "0.3125";
>     DisplayWhitePointY = "0.3291016";
>     DisplayYearManufacture = 2019;
>     IODisplayAttributes = {length = 40, bytes = 0x67617476 00000000 73676c66 04000000 ... 676c6664 00000000 };
>     IODisplayConnectFlags = {length = 4, bytes = 0x00080000};
>     IODisplayEDID = {length = 256, bytes = 0x00ffffff ffffff00 061044a0 00000000 ... 00000000 00000490 };
>     IODisplayEDIDOriginal = {length = 256, bytes = 0x00ffffff ffffff00 061044a0 00000000 ... 00000000 00000490 };
>     IODisplayHasBacklight = 1;
>     IODisplayIsDigital = 1;
>     IODisplayIsHDMISink = 0;
>     IODisplayLocation = "IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/PEG0@1/IOPP/EGP0@0/IOPP/EGP1@0/IOPP/GFX0@0/AMDRadeonX6000_AmdRadeonControllerNavi14/ATY,Boa@0/display0/AppleBacklightDisplay";
>     IODisplayMobileBLTable = {length = 36, bytes = 0x00110000 02900344 043d0592 076509e4 ... 583a7a96 aae1eeed };
>     IODisplayPrefsKey = "Alias:0/AppleBacklightDisplay-610-a044";
>     IOFBTransform = 0;
>     IOGFlags = 4;
>     "display-refresh-rate-policy" = {length = 8, bytes = 0x0000000000000001};
>     "display-resolution-preview-icon" = "/System/Library/Displays/Contents/Resources/Overrides/DisplayVendorID-610/DisplayProductID-a044-9d9da0.tiff";
>     "display-rotation-policy" = {length = 8, bytes = 0x0000000000000001};
>     dspc =     (
>         {length = 18, bytes = 0xd5910050c08038700820980859d71000001a},
>         {length = 18, bytes = 0xe7910050c080c2710820980859d71000001a},
>         {length = 18, bytes = 0xdc910050c08024720820980859d71000001a},
>         {length = 18, bytes = 0xe4910050c08027720820980859d71000001a}
>     );
>     "edid-patches" =     (
>                 {
>             data = {length = 36, bytes = 0x00000010 00000000 00000000 00000000 ... 00000000 00000000 };
>             offset = 90;
>         }
>     );
>     "resolution-preview-height" = 96;
>     "resolution-preview-width" = 154;
>     "resolution-preview-x" = 36;
>     "resolution-preview-y" = 65;
>     "scale-resolutions" =     (
>         {length = 8, bytes = 0x0000100000000a00},
>         {length = 8, bytes = 0x00000e00000008c0},
>         {length = 8, bytes = 0x00000c0000000780},
>         {length = 8, bytes = 0x00000a8000000690},
>         {length = 8, bytes = 0x00000900000005a0},
>         {length = 16, bytes = 0x00000a00000006400000000100200000},
>         {length = 16, bytes = 0x00000a00000005a00000000100200000},
>         {length = 16, bytes = 0x00000780000004b00000000100200000},
>         {length = 16, bytes = 0x00000780000004380000000100200000},
>         {length = 16, bytes = 0x00000500000002d00000000100200000},
>         {length = 12, bytes = 0x000006720000041a00000001},
>         {length = 12, bytes = 0x000005a00000038400000001},
>         {length = 12, bytes = 0x000005000000032000000001},
>         {length = 12, bytes = 0x00000480000002d000000001},
>         {length = 12, bytes = 0x000004000000030000000001},
>         {length = 12, bytes = 0x000003480000020d00000001},
>         {length = 12, bytes = 0x000003200000025800000001},
>         {length = 12, bytes = 0x00000280000001e000000001},
>         {length = 16, bytes = 0x00000f00000009600000000900a00000},
>         {length = 16, bytes = 0x00000d20000008340000000900a00000},
>         {length = 16, bytes = 0x00000b40000007080000000900a00000},
>         {length = 16, bytes = 0x00000a00000006400000000900a00000},
>         {length = 16, bytes = 0x00000800000005000000000900a00000},
>         {length = 16, bytes = 0x00000780000004b00000000900a00000},
>         {length = 16, bytes = 0x00000780000004380000000900200000},
>         {length = 16, bytes = 0x00000500000002d00000000900200000}
>     );
>     slopeLimitGamma = 0;
>     "target-default-ppmm" = "10.39";
> }), 458635451: Optional({
>     ContainerID = "DC8846F4-4A9F-45B5-B4B9-B43D7DE1CA37";
>     DisplayBluePointX = "0.1503906";
>     DisplayBluePointY = "0.05957031";
>     DisplayBrightnessAffectsGamma = 1;
>     DisplayBundleURL = "/System/Library/Displays/";
>     DisplayGreenPointX = "0.2646484";
>     DisplayGreenPointY = "0.6904297";
>     DisplayHasHardwareBrightnessSmoothing = 1;
>     DisplayHorizontalImageSize = 600;
>     DisplayPort =     {
>         PowerValue = 5;
>     };
>     DisplayProductID = 23412;
>     DisplayProductName =     {
>         ar = "LG UltraFine";
>         "ca_ES" = "LG UltraFine";
>         "cs_CZ" = "LG UltraFine";
>         "da_DK" = "LG UltraFine";
>         "de_DE" = "LG UltraFine";
>         "el_GR" = "LG UltraFine";
>         "en_AU" = "LG UltraFine";
>         "en_GB" = "LG UltraFine";
>         "en_US" = "LG UltraFine";
>         "es_ES" = "LG UltraFine";
>         "es_XL" = "LG UltraFine";
>         "fi_FI" = "LG UltraFine";
>         "fr_CA" = "LG UltraFine";
>         "fr_FR" = "LG UltraFine";
>         "he_IL" = "LG UltraFine";
>         "hi_IN" = "LG UltraFine";
>         "hr_HR" = "LG UltraFine";
>         "hu_HU" = "LG UltraFine";
>         id = "LG UltraFine";
>         "it_IT" = "LG UltraFine";
>         "ja_JP" = "LG UltraFine";
>         "ko_KR" = "LG UltraFine";
>         ms = "LG UltraFine";
>         "nb_NO" = "LG UltraFine";
>         "nl_NL" = "LG UltraFine";
>         "pl_PL" = "LG UltraFine";
>         "pt_BR" = "LG UltraFine";
>         "pt_PT" = "LG UltraFine";
>         "ro_RO" = "LG UltraFine";
>         "ru_RU" = "LG UltraFine";
>         "sk_SK" = "LG UltraFine";
>         "sv_SE" = "LG UltraFine";
>         "th_TH" = "LG UltraFine";
>         "tr_TR" = "LG UltraFine";
>         "uk_UA" = "LG UltraFine";
>         "vi_VN" = "LG UltraFine";
>         "zh_CN" = "LG UltraFine";
>         "zh_TW" = "LG UltraFine";
>     };
>     DisplayRedPointX = "0.6796875";
>     DisplayRedPointY = "0.3203125";
>     DisplaySerialNumber = 320951;
>     DisplayVendorID = 7789;
>     DisplayVerticalImageSize = 340;
>     DisplayWeekManufacture = 6;
>     DisplayWhiteGamma = "2.2";
>     DisplayWhitePointX = "0.3125";
>     DisplayWhitePointY = "0.3291016";
>     DisplayYearManufacture = 2020;
>     IODisplayAttributes = {length = 40, bytes = 0x67617476 00000000 73676c66 04000000 ... 676c6664 00000000 };
>     IODisplayConnectFlags = {length = 4, bytes = 0x00000000};
>     IODisplayEDID = {length = 256, bytes = 0x00ffffff ffffff00 9e6d745b b7e50400 ... 00000000 00005490 };
>     IODisplayEDIDOriginal = {length = 256, bytes = 0x00ffffff ffffff00 9e6d745b b7e50400 ... 00000000 00005490 };
>     IODisplayIsDigital = 1;
>     IODisplayIsHDMISink = 0;
>     IODisplayLocation = "IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/PEG0@1/IOPP/EGP0@0/IOPP/EGP1@0/IOPP/GFX0@0/AMDRadeonX6000_AmdRadeonControllerNavi14/ATY,Boa@1/display0/AppleDisplay";
>     IODisplayPrefsKey = "IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/PEG0@1/IOPP/EGP0@0/IOPP/EGP1@0/IOPP/GFX0@0/AMDRadeonX6000_AmdRadeonControllerNavi14/ATY,Boa@1/display0/AppleDisplay-9e6d-5b74";
>     IOFBTransform = 0;
>     IOGFlags = 4;
>     "display-icon" = "/System/Library/Displays/Contents/Resources/Overrides/DisplayVendorID-1e6d/DisplayProductID-5b74.icns";
>     "display-resolution-preview-icon" = "/System/Library/Displays/Contents/Resources/Overrides/DisplayVendorID-1e6d/DisplayProductID-5b74.tiff";
>     "resolution-preview-height" = 114;
>     "resolution-preview-width" = 202;
>     "resolution-preview-x" = 11;
>     "resolution-preview-y" = 47;
>     "scale-resolutions" =     (
>         {length = 8, bytes = 0x0000190000000e10},
>         {length = 8, bytes = 0x0000168000000ca8},
>         {length = 8, bytes = 0x0000140000000b40},
>         {length = 8, bytes = 0x0000100000000900},
>         {length = 8, bytes = 0x00000c8000000708},
>         {length = 16, bytes = 0x00001000000008700000000100200000},
>         {length = 16, bytes = 0x00000f00000008700000000100200000},
>         {length = 16, bytes = 0x00000a00000006400000000100200000},
>         {length = 16, bytes = 0x00000780000004b00000000100200000},
>         {length = 16, bytes = 0x000006900000041a0000000100200000},
>         {length = 16, bytes = 0x00000500000003200000000100200000},
>         {length = 12, bytes = 0x00000b400000065400000001},
>         {length = 12, bytes = 0x00000a00000005a000000001},
>         {length = 12, bytes = 0x000008000000048000000001},
>         {length = 12, bytes = 0x000007800000043800000001},
>         {length = 12, bytes = 0x00000640000004b000000001},
>         {length = 12, bytes = 0x000006400000038400000001},
>         {length = 12, bytes = 0x000005a00000032a00000001},
>         {length = 12, bytes = 0x00000540000002f400000001},
>         {length = 12, bytes = 0x000005000000040000000001},
>         {length = 12, bytes = 0x00000500000002d000000001},
>         {length = 12, bytes = 0x000004000000030000000001},
>         {length = 12, bytes = 0x000004000000024000000001},
>         {length = 12, bytes = 0x000003c00000025800000001},
>         {length = 12, bytes = 0x000003c00000021c00000001},
>         {length = 12, bytes = 0x000003480000020c00000001},
>         {length = 12, bytes = 0x000003200000025800000001},
>         {length = 12, bytes = 0x00000280000001e000000001},
>         {length = 16, bytes = 0x0000190000000e100000000900a00000},
>         {length = 16, bytes = 0x0000168000000ca80000000900a00000},
>         {length = 16, bytes = 0x0000140000000b400000000900a00000},
>         {length = 16, bytes = 0x00001000000009000000000900a00000},
>         {length = 16, bytes = 0x00000c80000007080000000900a00000}
>     );
>     slopeLimitGamma = 0;
> })]
> ```

Hello! If you have problem with adjusting of brightness of LG 27md5kl-b use this:
https://github.com/MonitorControl/MonitorControl
