### ISSUE TITLE
Not working in Big Sur

### ISSUE THREAD

**Issue by amarquez21** [OCJvanDijk/Brightness-Sync#21]
This isn't currently working on 11.0.1, will there be an update soon?

**Comment by OCJvanDijk** [comment]
Hey,

I just upgraded to 11.0.1 myself and it's working fine for me.
Do you have any more info? Does it crash on startup? Does it not sync?

**Comment by amarquez21** [comment]
I have this model: https://www.lg.com/us/monitors/lg-27un850-w-4k-uhd-led-monitor

Maybe my monitor isn't compatible?

**Comment by OCJvanDijk** [comment]
Yes, it's not compatible. This app is specifically for LG UltraFine displays. There are other apps that might help you, like https://github.com/alin23/Lunar

**Comment by amarquez21** [comment]
That worked for me, thank you sir!
