### ISSUE TITLE
Displays not detected after connecting in Big Sur

### ISSUE THREAD

**Issue by OCJvanDijk** [OCJvanDijk/Brightness-Sync#22]
When I plug in my display with the app running, the app doesn't detect it and it stays "Deactivated".

Workaround: Restart the app

I'll investigate soon when I have a bit more time.

**Comment by OCJvanDijk** [comment]
Should be fixed in v2.3.0

**Comment by OCJvanDijk** [comment]
Reopening because I'm still experiencing this sometimes.

**Comment by OCJvanDijk** [comment]
Seems to mostly happen to me now when waking from sleep.

**Comment by mustdobetter** [comment]
Agreed - I also experience this intermittently when waking from sleep. This usually only affects one of the two UltraFine 5k's (1st gen) that are plugged in. Restarting the app always sorts it out.

**Comment by AdeTheux** [comment]
No problem to report since 2.30 update with 1 5k (1st gen monitor).

**Comment by OCJvanDijk** [comment]
Try out v2.3.1.
It is much more robust, I know this because I've stared at the code for a long time. (Actually testing this is hard, ok, it's all barely reproducible. I haven't had an issue with it yet at least.)

**Comment by mustdobetter** [comment]
Thanks @OCJvanDijk - having used this for a few days now I haven't experienced the issue again. Good code-staring 😄

**Comment by OCJvanDijk** [comment]
👍. I also haven't experienced the issue anymore, so I'm going to close it again.

I even seem to have solved the offset shift issue, so I might remove the offset lock, which is just confusing everybody.
