### ISSUE TITLE
Not working on LG 27UL850

### ISSUE THREAD

**Issue by rgaufman** [OCJvanDijk/Brightness-Sync#23]
I tried connecting to MacBook Pro 13" on Big Sur using provided USB-C cable, and I see this: 
<img width="260" alt="Screenshot 2020-11-27 at 16 51 44" src="https://user-images.githubusercontent.com/33842342/100470802-d8966d80-30d0-11eb-87f9-57957d17e3b6.png">

I also tried the same on Hackintosh running Catalina, connecting display via DisplayPort and also via USB-C, seeing the same result of "Deactivated".

Any ideas?

Update: I installed the Lunar app and it works there

**Comment by OCJvanDijk** [comment]
This app only works with UltraFine displays. UltraFine displays have a special brightness control mechanism that's different from other displays. I want to keep this app very focused, and Lunar is already a great app for other displays.
