### ISSUE TITLE
App takes a lot of CPU time on M1 MacBook Air...

### ISSUE THREAD

**Issue by rsaid99** [OCJvanDijk/Brightness-Sync#25]
App is consistently taking 7-8% of CPU time on 2020 MBA M1.  I was expecting/hoping for <1%...normal?

<img width="526" alt="Screen Shot 2020-12-05 at 12 11 37 AM" src="https://user-images.githubusercontent.com/58244275/101237681-9e5c3b80-368f-11eb-9447-dfd8b5a33546.png">

**Comment by OCJvanDijk** [comment]
I'm just going to close this in favor of #24
