### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by chmac** [OCJvanDijk/Brightness-Sync#34]
Thanks A LOT for this app. The usual story, brightness worked on the screen, then stopped, then wouldn't do anything. Googling around, what the hell, this is supposed to "just work", blah, blah, blah. The with one cask install, my brightness woes are a distant memory. A heroic contribution to open source, thank you kindly indeed.

**Comment by OCJvanDijk** [comment]
Thank you for the kind words!
