### ISSUE TITLE
Brightness on monitors flickers up and down

### ISSUE THREAD

**Issue by chmac** [OCJvanDijk/Brightness-Sync#36]
I've just rebooted my MacBook Pro. When I adjust the brightness with my touchbar, I now get 3 sliders, one for the internal display, and one for each of the external 5k ultrafine displays. However, when this app is running, the brightness flickers up and down on both monitors. If I "pause" this app, it stops flickering.

I seem to remember that the first time I plugged in the monitors, I could adjust their brightness on the touchbar. But after the first time they were unplugged, the option no longer appeared, and I could only adjust the brightness on 1. If you have any suggestions as to how I can investigate what the issue is, post logs, etc, I'll be happy to try.

Thanks again for this app. :-)

**Comment by OCJvanDijk** [comment]
Hi,

Are you using v2.3.2 or the beta?
Do you have the brightness offset “lock” on?
Are these 2nd generation displays and if so, did you turn off the system automatic brightness in the settings?

**Comment by chmac** [comment]
@OCJvanDijk 

1: I'm using 2.3.2
2: Yes, the brightness lock is on.
3: Oh, yes, I think they are 2nd generation displays, and I have the "automatically adjust brightness" setting set to on for each fo the displays.

I hadn't noticed the brightness slider on the displays. That didn't show up when I first plugged in the screens. I guess the issue is the interaction between the sync app and the automatic adjustment on the screens themselves?

Sorry about this, I think this is a spurious bug report. I can imagine that having the monitors adjusting their own brightness and using the sync app probably won't work well together. I'll close this issue now. But if I'm missing something, and you think there is a bug to investigate, feel free to reopen and I'll try to assist debugging if I can.

**Comment by OCJvanDijk** [comment]
No problem!

If turning off the system automatic brightness for the displays solves the problem, then everything is working as expected. Indeed, the automatic brightness would just get overridden again immediately and I'd imagine that could cause flickering.

**Comment by chmac** [comment]
@OCJvanDijk Yep, just ran some tests having disabled auto brightness, and sure enough, monitors all stay in sync, works like a charm! Thanks again for this app and the support. 👍 👍 👍
