### ISSUE TITLE
Flickering when light changes

### ISSUE THREAD

**Issue by CM-NZ** [OCJvanDijk/Brightness-Sync#40]
I'm using the Apple Silicon beta version with an LG Ultrafine external display. When the light changes, the app causes the screen to flicker light and dark for a few seconds before it settles down.

**Comment by cbowns** [comment]
Which machine are you on? I've had no issues on an M1 Air + LG 5K

**Comment by CM-NZ** [comment]
Hi Thanks for your response. I realised that I had the auto brightness turned on in the Mac system preferences at the same time so was fighting with your app causing the flickering :)

C
