### ISSUE TITLE
Not working in Monterey?

### ISSUE THREAD

**Issue by rothaar** [OCJvanDijk/Brightness-Sync#41]
I've noticed that this doesn't seem to work for me with my LG UltraFine since I updated to Monterey.

It probably isn't specific to Brightness-Sync (I have trouble even in the Display Settings panel) but I was hoping this could help!

**Comment by cbowns** [comment]
If you're seeing issues in the Display prefs, then it's unlikely that Brightness Sync can do much for you.

(What are you seeing in Displays? And, have you rebooted at least once since updating? I had several display config issues on my M1's first Monterey boot but it's been fine since then.)

**Comment by rothaar** [comment]
Hi! Sorry for the long delay. Yes, it turns out that just rebooting another time helped resolve whatever was up and Brightness Sync, and Displays, are controlling the second monitor properly again!

Thanks!
