### ISSUE TITLE
No issue - but a nice side effect

### ISSUE THREAD

**Issue by rosch100** [OCJvanDijk/Brightness-Sync#6]
Just to let you know, that it works with my old 22" Cinema HD display as well.
Thanks a lot!

**Comment by rosch100** [comment]
Just discovered that the effect was a side effect of another tool ("Brightness.app"). Combined, both tools give optimum results.

**Comment by OCJvanDijk** [comment]
Ah ok 🙂. That would have been a bug because it’s only supposed to detect UltraFine displays, in order to correctly turn off when none are connected. So you have both a Cinema Display and an UltraFine connected? Glad to hear it’s working for you.
