### ISSUE TITLE
Consider adding the package to Brew Cask

### ISSUE THREAD

**Issue by bnice5000** [OCJvanDijk/Brightness-Sync#8]
Right now the upgrade feature relies on manually going to the GitHub website. It would be useful if the application could be installed and updated from brew cask.

https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md

**Comment by OCJvanDijk** [comment]
Looks like I can do that now that the project has >50 stars :)

**Comment by OCJvanDijk** [comment]
Opened a pull request to Brew Cask: https://github.com/Homebrew/homebrew-cask/pull/79681

**Comment by OCJvanDijk** [comment]
We're live!
`$ brew cask install brightness-sync`
