### ISSUE TITLE
True Tone

### ISSUE THREAD

**Issue by mustdobetter** [OCJvanDijk/Brightness-Sync#9]
This isn't an issue, but rather new behaviour I've noticed since purchasing a MacBook Pro 16" with True Tone display ("this is a bug not a feature"). As well as syncing the brightness, my 2x LG UltraFine 5ks seem now to change tone along with the MacBook Pro screen e.g. if the ambient light becomes more yellow, all 3 displays change in accordance, and become more yellow. @OCJvanDijk, I imagine this is a happy side effect of the way you've implemented the brightness syncing, but wondered whether you were aware of this, or possibly had even considered this?

Anyway, as I say, not an issue at all, as it works really well!

**Comment by OCJvanDijk** [comment]
Not my doing, it's a feature of macOS itself and should work without Brightness Sync: 
https://support.apple.com/en-us/HT208909 (scroll down to "True Tone on external displays")
I've always thought it was very odd Apple would sync True Tone but not brightness to UltraFine displays...

**Comment by mustdobetter** [comment]
Ah I didn’t realise it was part of MacOS. I guess that was introduced in Catalina as it’s certainly only recently that I noticed this happening, and it’s fairly obvious. I agree though; how odd to sync tone but not brightness.
